package com.example.ghansarvatobhadra

import android.content.Context
import android.os.Environment
import com.itextpdf.kernel.colors.DeviceRgb
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Cell
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.TextAlignment
import com.itextpdf.layout.properties.UnitValue
import java.io.File

object PdfExporter {

    fun export(
        context: Context,
        name: String, date: String, time: String, place: String,
        lat: Double, lon: Double, chart: ChartResponse
    ): File {
        val safeName = name.ifBlank { "user" }.replace(" ", "_")
        val file = File(
            context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS),
            "Sarvatobhadra_${safeName}_${System.currentTimeMillis()}.pdf"
        )

        val doc = Document(PdfDocument(PdfWriter(file)))

        doc.add(Paragraph("घन सर्वतोभद्र चक्र")
            .setFontSize(22f).setBold().setTextAlignment(TextAlignment.CENTER)
            .setFontColor(DeviceRgb(106, 27, 154)))
        doc.add(Paragraph("Ghan Sarvato Bhadra — Vedic Chart Report")
            .setFontSize(11f).setTextAlignment(TextAlignment.CENTER))
        doc.add(Paragraph("\n"))

        doc.add(Paragraph("जन्म विवरण / Birth Details").setBold().setFontSize(13f))
        doc.add(Paragraph("नाम / Name: $name"))
        doc.add(Paragraph("दिनांक / Date: $date"))
        doc.add(Paragraph("समय / Time: $time"))
        doc.add(Paragraph("स्थान / Place: $place"))
        doc.add(Paragraph("Latitude: $lat   Longitude: $lon"))
        doc.add(Paragraph("\n"))

        doc.add(Paragraph("सर्वतोभद्र चक्र / Chart").setBold().setFontSize(13f))
        val table = Table(UnitValue.createPercentArray(9)).useAllAvailableWidth()
        for (r in 0..8) for (c in 0..8) {
            val label = SarvatobhadraEngine.labels[r][c]
            table.addCell(Cell().add(Paragraph(label).setFontSize(6.5f)))
        }
        doc.add(table)
        doc.add(Paragraph("\n"))

        doc.add(Paragraph("ग्रह स्थिति / Planetary Positions").setBold().setFontSize(13f))
        chart.bodies.forEach { p ->
            val nak = AstrologyConstants.nakshatras[p.nakshatraIndex]
            val rash = AstrologyConstants.rashis[p.rashi - 1]
            val retro = if (p.retrograde) " (R)" else ""
            doc.add(Paragraph("${p.planet.uppercase()}: ${"%.2f".format(p.longitude)}° — $rash, $nak P${p.pada}$retro"))
        }
        doc.add(Paragraph("\n"))

        val moon = chart.bodies.firstOrNull { it.planet.equals("moon", true) }
        val natal = SarvatobhadraEngine.natalPoints(moon, chart.lagna, name, chart.tithi, chart.weekday)
        doc.add(Paragraph("नतल पॉइंट्स / Natal Points").setBold().setFontSize(13f))
        natal.forEach { doc.add(Paragraph("• ${it.label} → ${SarvatobhadraEngine.labels[it.row][it.col]}")) }
        doc.add(Paragraph("\n"))

        val hits = SarvatobhadraEngine.hits(chart.bodies)
        doc.add(Paragraph("वेध / Vedha Hits").setBold().setFontSize(13f))
        hits.take(100).forEach {
            doc.add(Paragraph("• ${it.planet} ${it.direction} → ${it.targetLabel} (${it.nature})"))
        }

        doc.add(Paragraph("\n\nGenerated by Ghan Sarvato Bhadra App").setFontSize(8f))
        doc.close()
        return file
    }
}
